hydra:
    run:
        dir: .

logging_config_path: configs/logging_config.yaml
input_data_path: data/raw/heart.csv
output_model_path: models/model_logreg.pkl
metric_path: models/metrics_logreg.json
splitting_params:
    val_size: 0.1
    random_state: 42
feature_params:
    categorical_features: []
    numerical_features:
        - age
        - sex
        - cp
        - trestbps
        - chol
        - fbs
        - restecg
        - thalach
        - exang
        - oldpeak
        - slope
        - ca
        - thal
    target_col: target
training_params:
    model_type: LogisticRegression
    model_params:
        C: 0.1
        max_iter: 1000
    random_state: 42
