name: pylint and tests runner
on:
  push:
    branches:
      - homework1
defaults:
  run:
    working-directory: ./ml_project/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pytest
    - name: run pylint
      run: |
        pylint -d missing-function-docstring,missing-module-docstring,missing-class-docstring,logging-fstring-interpolation,invalid-name heart_classification/
    - name: run tests
      run: |
        pytest tests/
